### PR TITLE
Implementation of SQLSetDescRec & SQLGetDescRec functions

### LINKED ISSUE #21: Plan to implement SQLSetDescRec & SQLGetDescRec functions
Currently, psqlodbc lacks support for SQLSetDescRec and SQLGetDescRec functions. Any idea why these functions are not implemented yet? 

I plan to implement these functions and will open a PR in few days. Any ideas or suggestions regarding the implementation would be greatly appreciated.

### PR DESCRIPTION
**Pull request by Hunaid2000**
Resolves #21.

- Completed implementation of `SQLSetDescRec` function.
- Fixed `SQL_DESC_PRECISION` field in `IPDSetField` & `IPDGetField` functions.
- Added support for following fields for bookmark column in `ARDSetField` .
    - SQL_DESC_TYPE
    - SQL_DESC_DATETIME_INTERVAL_CODE
    - SQL_DESC_OCTET_LENGTH
    - SQL_DESC_PRECISION
    - SQL_DESC_SCALE

**Note:**
I am now working on `SQLGetDescRec` implementation.

### CODE REVIEW

**Comment by Hunaid2000** [comment]
Implementation for both functions is completed.

Other changes:
- Handled SQL_NO_DATA case in GetField functions
- Handled 01004 SQLSTATE in GetField functions
- Added support for SQL_DESC_NAME & SQL_DESC_NULLABLE in IPDGetField function

**Comment by Hunaid2000** [comment]
@davecramer any update on this?

**Comment by davecramer** [comment]
@Hunaid2000 Ideally we would add tests for these new functions ? 
Any chance you can add them ?

**Comment by Hunaid2000** [comment]
I will try to add them.

**Comment by Hunaid2000** [comment]
@davecramer I have added regression test.

**Pull request merged**
