### PR TITLE
Use WiX 5

### PR DESCRIPTION
**Pull request by chrullrich**
This branches from my other MSI branch. x64 and x86 build and work.

See the README for how to install what bits of WiX are needed.

WiX 5 does not use the file name in the key of the File table by default; I have changed modify_msi.vbs to identify its target files by the component ID instead ... and most recently by the file name itself.

### CODE REVIEW

**Comment by chrullrich** [comment]
I don't think there is more that needs to be done here this side of adding the arm64 package.

**Comment by davecramer** [comment]
I just have to now figure out why it fails

**Comment by davecramer** [comment]
Thanks so much for this!

**Comment by chrullrich** [comment]
> I just have to now figure out why it fails

I saw that. Have another commit.

**Comment by davecramer** [comment]
cool, thanks so much

**Pull request merged**
